### ISSUE TITLE
About the environment install

### ISSUE THREAD

**Issue by liusy58** [DreamAndDead/CSAPP-3e-Solutions#58]
Hey ,After I entered "make plugin"

Following errors occured:
Error loading version latest: SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/gitbook/.gitbook/versions/3.2.3/node_modules/read-installed/node_modules/read-package-json/read-json.js:14:27)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

TypeError: Cannot read property 'commands' of null

Could you plz tell me how to solve it?

**Comment by MikeMMS** [comment]
did you get a solution? I just come across the same issue now.

**Comment by MikeMMS** [comment]
I just figured out a workaround: 
1. install npm: sudo 
apt install npm
2. install gitbook: 
npm install gitbook
3. gitbook init
4. gitbook install
5. gitbook serve --no-watch
then you can open localhost: 4000 and see the book.
If you want to make pdf or HTML file etc, you could use cat makefile to check the corresponding gitbook command

**Comment by liusy58** [comment]
thx, I'll have a try
