### ISSUE TITLE
Run make plugin error

### ISSUE THREAD

**Issue by peng051410** [DreamAndDead/CSAPP-3e-Solutions#66]
When i run `make plugin`, got error:
`
Error loading version latest: SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/gitbook/.gitbook/versions/3.2.3/node_modules/read-installed/node_modules/read-package-json/read-json.js:7:16)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

TypeError: Cannot read property 'commands' of null
`

What should i do?

**Comment by Zhangjiajia6** [comment]
I met exactly the same issue here.
